# Mode: just epaxos replication

mode:
  cc: epaxos # concurrency control
  ab: epaxos # atomic broadcast
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# Sites: 1 server, 3 replicas
site:
  server:
    - ["s101:8101", "s102:8102", "s103:8103"]
  client: # each line is a partition
    - ["c01"]

process:
  s101: p1
  s102: p2
  s103: p3
  c01: localhost

host:
  p1: 127.0.0.1
  p2: 127.0.0.1
  p3: 127.0.0.1
  localhost: 127.0.0.1
