
# config/rw.yml 
bench:
  workload: rw
  scale: 1
  weight:
    read: 0 
    write: 1
  population: # intial number of records in each table
    history: 1000000

schema: # table information
  - name: history
    column:
      - {name: h_key,     type: integer, primary: true}
      - {name: h_c_id,    type: integer}

# sharding strategy.
# default is MOD by primary key.
# CUSTOM means strategy is defined in the code.
# TODO a better way to define sharding strategy.
sharding:
  history:    MOD

# config/2pl_ww_fpga_raft.yml
mode:
  cc: none # concurrency control
  ab: chain_rpc # atomic broadcast; chain_rpc
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# config/concurrent_100.yml 
n_concurrent: 100

# config/1c1s3r3p.yml
# site:
#   server: # each line is a partition, the first is the master site_name:port
#     - ["s101:8000", "s201:8001", "s301:8002"]
#   client: # each line is a partition
#     - ["c101"]

# # site_name - process_name map
# process:
#   s101: p1
#   s201: p2
#   s301: p3
#   c101: localhost

# host:
#   localhost: 127.0.0.1
#   p1: 127.0.0.1
#   p2: 127.0.0.1
#   p3: 127.0.0.1

# config/1c1s3r1p.yml
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:28000", "s201:28001", "s301:28002"]
  client: # each line is a partition
    - ["c01", "c02", "c03"]

# site_name - process_name map
process:
  s101: localhost 
  s201: p1 
  s301: p2 
  c01: c01 
  c02: c02
  c03: c03

host:
  localhost: 192.168.1.102 
  p1: 192.168.1.103
  p2: 192.168.1.104
  c01: 192.168.1.102
  c02: 192.168.1.102
  c03: 192.168.1.102
